name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Start SonarQube Server
        run: |
          docker pull sonarqube:latest
          docker run -d -p 9000:9000 sonarqube:latest
      - name: Wait for SonarQube to Start
        run: |
          echo "Waiting for SonarQube to start..."
          for i in {1..30}; do
            curl -s http://localhost:9000/api/system/health | grep -q '"status":"GREEN"' && break
            sleep 5
          done
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
