<<<<<<< HEAD
name: CI Pipeline

on:
  pull_request:
    branches: [develop]

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install flake8 black

      - name: Запуск flake8 через Reviewdog
        uses: reviewdog/action-flake8@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error

      - name: Запуск Black через Reviewdog
        uses: reviewdog/action-black@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: info

      - name: Count lines of code with Cloc
        run: |
          sudo apt-get install -y cloc
          cloc src/ > cloc-report.txt
          cat cloc-report.txt

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli-4.8.0.2856-linux.zip
          export PATH=$PATH:$(pwd)/sonar-scanner-4.8.0.2856-linux/bin
          sonar-scanner
=======
name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Start SonarQube Server
        run: |
          docker pull sonarqube:latest
          docker run -d -p 9000:9000 sonarqube:latest
      - name: Wait for SonarQube to Start
        run: |
          echo "Waiting for SonarQube to start..."
          for i in {1..30}; do
            curl -s http://localhost:9000/api/system/health | grep -q '"status":"GREEN"' && break
            sleep 5
          done
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
>>>>>>> 3fe26800a41f1291573b38862c483a1eb69a56cc
